version: '3.7'
services:
  db:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_USER: bot_admin
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: gametest1
    ports:
      - 5432:5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  rabbit:
    image: rabbitmq:3.8-alpine
    restart: always
    ports:
      - 5672:5672
#    healthcheck:
#      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
#      interval: 10s
#      timeout: 10s
#      retries: 5

  web:
    restart: always
    build: .
    ports:
      - 8001:8001
    depends_on:
      - db
      - rabbit
    command: python main.py web

  worker:
    restart: always
    build: .
    depends_on:
      - db
      - rabbit
    command: python -m app.worker.worker
    environment:
      AMQP_URL: 'amqp://rabbit?connection_attempts=5&retry_delay=5'

  longpoll:
    restart: always
    build: .
    depends_on:
      - db
      - rabbit
    command: python -m app.vk.longpoll