version: '3.7'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: bot_admin
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: db_bot
    ports:
      - 5432:5432

  rabbit:
    image: rabbitmq:3.8-alpine
    restart: always
    ports:
      - 5672:5672

  web:
    restart: always
    build: .
    ports:
      - 8001:8001
    depends_on:
      - db
      - rabbit
    command: python main.py web

  worker:
    restart: always
    build: .
    depends_on:
      - db
      - rabbit
    command: python -m app.worker.worker
    environment:
      AMQP_URL: 'amqp://rabbit?connection_attempts=5&retry_delay=5'

  longpoll:
    restart: always
    build: .
    depends_on:
      - db
      - rabbit
    command: python -m app.vk.longpoll