"""user added

Revision ID: 1a62c74f47d5
Revises: da72391c1378
Create Date: 2021-02-19 20:47:46.490010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a62c74f47d5'
down_revision = 'da72391c1378'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
