"""question added

Revision ID: 244bc3b6b726
Revises: e75aed8cba85
Create Date: 2021-02-19 21:58:16.247381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244bc3b6b726'
down_revision = 'e75aed8cba85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
