"""answer title fix 2

Revision ID: 6f72de710035
Revises: a95829df82dc
Create Date: 2021-02-20 17:59:23.753783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f72de710035'
down_revision = 'a95829df82dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
