"""answer title fix 3

Revision ID: a91e50f90b1c
Revises: 6f72de710035
Create Date: 2021-02-20 18:05:13.422872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a91e50f90b1c'
down_revision = '6f72de710035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
