"""answer title fix 1

Revision ID: a95829df82dc
Revises: 8ea81551eeb3
Create Date: 2021-02-20 17:58:35.951777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95829df82dc'
down_revision = '8ea81551eeb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
