"""user added

Revision ID: f8b8e7349654
Revises: 1a62c74f47d5
Create Date: 2021-02-19 20:49:47.231523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b8e7349654'
down_revision = '1a62c74f47d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
