common:
  # каждый раз heroku выделяет разные порты,
  # поэтому необходимо вынести это в переменную
  port: $PORT
vk:
  access_token: $VK_ACCESS_TOKEN
  group_id: $VK_GROUP_ID
  v: 5.38
rabbitmq:
  url: amqp://guest:guest@localhost/
  queue_name: vkbot_test11
postgres:
  database_url: postgres://bot_admin:test_password@localhost/gametest1
  require_ssl: false
database:
  host: localhost
  port: 5432
  username: bot_admin
  password: test_password
  name: gametest1