common:
  # каждый раз heroku выделяет разные порты,
  # поэтому необходимо вынести это в переменную
  port: $PORT
vk:
  access-token: $VK_ACCESS_TOKEN
  group-id: $VK_GROUP_ID
  v: 5.38
rabbitmq:
  host: localhost
  queue_name: vkbot_test3