common:
  port: $PORT
vk:
  access_token: $VK_ACCESS_TOKEN
  group_id: $VK_GROUP_ID
  v: 5.38
  bot_name: py_jeopardy_bot
rabbitmq:
  url: amqp://guest:guest@localhost/
  queue_name: jeopardy_queue
postgres:
  database_url: $DATABASE_URL
  require_ssl: true
database:
  host: $DATABASE_HOST
  port: $DATABASE_PORT
  username: $DATABASE_USER
  password: $DATABASE_PASSWORD
  name: $DATABASE_NAME