common:
  # каждый раз heroku выделяет разные порты,
  # поэтому необходимо вынести это в переменную
  port: $PORT
vk:
  access-token: $VK_ACCESS_TOKEN
  group-id: $VK_GROUP_ID
  v: 5.38
rabbitmq:
  url: amqp://guest:guest@localhost/
  queue_name: vkbot_test5
postgres:
  database_url: postgres://postgres:@localhost/test_db
  require_ssl: false
database:
  host: localhost
  port: 5432
  username: $PG_USER
  password: $PG_PASSWORD
  name: $DB