common:
  # каждый раз heroku выделяет разные порты,
  # поэтому необходимо вынести это в переменную
  port: 14337
vk:
  access-token: $VK_ACCESS_TOKEN
  confirmation-token: $VK_CALLBACK_TOKEN
  group-id: $VK_GROUP_ID
  v: 5.130