common:
  port: 8002
vk:
  access_token: $VK_ACCESS_TOKEN
  group_id: $VK_GROUP_ID
  v: 5.38
  bot_name: py_jeopardy_bot
rabbitmq:
  url: amqp://guest:guest@localhost/
  queue_name: vkbot_test11
postgres:
  database_url: postgres://postgres:postgres@localhost/test_jeopardy
  require_ssl: false
database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  name: test_jeopardy