common:
  port: 8002
postgres:
  database_url: postgres://postgres:postgres@localhost/test_jeopardy
  require_ssl: false
database:
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  name: test_jeopardy