# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: jeopardy
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#    - name: Code style
#      run: |
#        black --check --diff .
    - name: Test with pytest
      env:
        CONFIG_PATH: config/tests.yaml
      run: |
        alembic upgrade head
        pytest -s tests/
    - name: Heroku deploy
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        heroku container:login
        heroku container:push -a py-jeopardy web --arg PROCESS_TYPE=web
        heroku container:push -a py-jeopardy worker --arg PROCESS_TYPE=worker
        heroku container:push -a py-jeopardy worker --arg PROCESS_TYPE=longpoll
        heroku container:release -a py-jeopardy web worker